"""User-assisted point picker for sticker-center clicks."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from PIL import Image

from .capture_guide import DEFAULT_CAPTURE_PRESET


POINT_PLANS = {
    "photo_1": [("U", "white"), ("F", "green"), ("L", "orange")],
    "photo_2": [("D", "yellow"), ("B", "blue"), ("R", "red")],
}


class PointPickerError(ValueError):
    """Raised when point picker input is invalid."""


def build_point_plan(image_role: str) -> list[dict[str, Any]]:
    """Build ordered sticker labels for one supported image role."""
    if image_role not in POINT_PLANS:
        raise PointPickerError(f"Unsupported image role: {image_role}.")

    plan = []
    for face, expected_color in POINT_PLANS[image_role]:
        for index in range(9):
            plan.append(
                {
                    "label": f"{face}{index}",
                    "face": face,
                    "index": index,
                    "expected_color": expected_color,
                }
            )
    return plan


def build_point_payload(image_role: str, clicked_points: list[dict[str, int]]) -> dict[str, Any]:
    """Build sampler-compatible JSON payload from clicked coordinates."""
    plan = build_point_plan(image_role)
    if len(clicked_points) != len(plan):
        raise PointPickerError(
            f"Expected {len(plan)} clicked points for {image_role}, got {len(clicked_points)}."
        )

    points = []
    for planned, clicked in zip(plan, clicked_points):
        points.append(
            {
                **planned,
                "x": clicked["x"],
                "y": clicked["y"],
            }
        )

    return {
        "image_role": image_role,
        "capture_preset": DEFAULT_CAPTURE_PRESET,
        "note": "Generated by point picker. Coordinates are sticker-center clicks.",
        "points": points,
    }


def ensure_output_path(output_path: str | Path, force: bool = False) -> Path:
    """Prepare output path and enforce overwrite rules."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not force:
        raise PointPickerError(
            f"Output file already exists: {path}. Use --force to overwrite it."
        )
    return path


def write_point_file(
    output_path: str | Path,
    image_role: str,
    clicked_points: list[dict[str, int]],
    *,
    force: bool = False,
) -> Path:
    """Write point picker output JSON to disk."""
    path = ensure_output_path(output_path, force=force)
    payload = build_point_payload(image_role, clicked_points)
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return path


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="rubiks-point-picker",
        description=(
            "Open an image, click sticker centers in order, and save a sample-points JSON file."
        ),
    )
    parser.add_argument("--image", required=True, help="Path to the input image.")
    parser.add_argument(
        "--image-role",
        required=True,
        choices=["photo_1", "photo_2"],
        help="Which capture role this image uses.",
    )
    parser.add_argument("--output", required=True, help="Path to the output JSON file.")
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite the output JSON file if it already exists.",
    )
    return parser


def run_point_picker(
    image_path: str | Path,
    image_role: str,
    output_path: str | Path,
    *,
    force: bool = False,
) -> Path:
    """Launch Tkinter point picker and write JSON when finished."""
    image_file = Path(image_path)
    if not image_file.exists():
        raise PointPickerError(f"Image file not found: {image_file}")

    output_file = ensure_output_path(output_path, force=force)
    plan = build_point_plan(image_role)

    import tkinter as tk
    from tkinter import messagebox
    from PIL import ImageTk

    with Image.open(image_file) as source_image:
        original_image = source_image.convert("RGB")

    root = tk.Tk()
    root.title(f"Point Picker - {image_role}")

    screen_width = max(root.winfo_screenwidth() - 100, 400)
    screen_height = max(root.winfo_screenheight() - 160, 400)
    image_width, image_height = original_image.size
    scale = min(screen_width / image_width, screen_height / image_height, 1.0)
    display_size = (max(1, int(image_width * scale)), max(1, int(image_height * scale)))
    display_image = original_image.resize(display_size, Image.Resampling.LANCZOS)

    tk_image = ImageTk.PhotoImage(display_image)
    state = {
        "points": [],
    }

    status_var = tk.StringVar()

    def update_status() -> None:
        if len(state["points"]) < len(plan):
            current = plan[len(state["points"])]
            status_var.set(
                f"Click {current['label']} ({len(state['points']) + 1}/{len(plan)})"
            )
        else:
            status_var.set("All points captured. Saving...")

    def redraw() -> None:
        canvas.delete("marker")
        for item in state["points"]:
            display_x = item["display_x"]
            display_y = item["display_y"]
            label = item["label"]
            canvas.create_oval(
                display_x - 6,
                display_y - 6,
                display_x + 6,
                display_y + 6,
                outline="red",
                width=2,
                tags="marker",
            )
            canvas.create_text(
                display_x + 14,
                display_y - 10,
                text=label,
                fill="red",
                anchor="w",
                tags="marker",
            )

    def finish() -> None:
        payload_points = [{"x": item["x"], "y": item["y"]} for item in state["points"]]
        write_point_file(output_file, image_role, payload_points, force=True)
        messagebox.showinfo("Point Picker", f"Saved {len(payload_points)} points to {output_file}")
        root.destroy()

    def handle_click(event: tk.Event) -> None:
        if len(state["points"]) >= len(plan):
            return
        planned = plan[len(state["points"])]
        original_x = max(0, min(image_width - 1, round(event.x / scale)))
        original_y = max(0, min(image_height - 1, round(event.y / scale)))
        state["points"].append(
            {
                "label": planned["label"],
                "x": original_x,
                "y": original_y,
                "display_x": event.x,
                "display_y": event.y,
            }
        )
        redraw()
        if len(state["points"]) == len(plan):
            update_status()
            finish()
        else:
            update_status()

    def undo_last(_event: tk.Event | None = None) -> None:
        if state["points"]:
            state["points"].pop()
            redraw()
            update_status()

    def cancel() -> None:
        root.destroy()

    top_frame = tk.Frame(root)
    top_frame.pack(fill="x", padx=8, pady=8)

    tk.Label(top_frame, textvariable=status_var, anchor="w").pack(side="left")
    tk.Button(top_frame, text="Undo", command=undo_last).pack(side="right", padx=4)
    tk.Button(top_frame, text="Cancel", command=cancel).pack(side="right")

    canvas = tk.Canvas(root, width=display_size[0], height=display_size[1], cursor="crosshair")
    canvas.pack(padx=8, pady=8)
    canvas.create_image(0, 0, anchor="nw", image=tk_image)
    canvas.bind("<Button-1>", handle_click)
    root.bind("<BackSpace>", undo_last)
    root.bind("<Escape>", lambda _event: cancel())

    update_status()
    root.mainloop()

    if not output_file.exists():
        raise PointPickerError("Point picking was cancelled before saving.")

    return output_file


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        output_file = run_point_picker(
            args.image,
            args.image_role,
            args.output,
            force=args.force,
        )
    except PointPickerError as exc:
        print(f"Error: {exc}")
        return 2

    print(f"Saved point file: {output_file}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
